package com.noemi.worldcountries.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8B0000)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC91A0F)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFFA63A2C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF8E7D)
val onSecondaryContainerLight = Color(0xFF4F0000)
val tertiaryLight = Color(0xFF5C3C00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF885E12)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF281715)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF281715)
val surfaceVariantLight = Color(0xFFFFDAD4)
val onSurfaceVariantLight = Color(0xFF5C403B)
val outlineLight = Color(0xFF916F6A)
val outlineVariantLight = Color(0xFFE6BDB7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3F2C29)
val inverseOnSurfaceLight = Color(0xFFFFEDEA)
val inversePrimaryLight = Color(0xFFFFB4A8)

val primaryDark = Color(0xFFFFB4A8)
val onPrimaryDark = Color(0xFF690000)
val primaryContainerDark = Color(0xFFA20000)
val onPrimaryContainerDark = Color(0xFFFFE8E4)
val secondaryDark = Color(0xFFFFB4A8)
val onSecondaryDark = Color(0xFF650904)
val secondaryContainerDark = Color(0xFF801E13)
val onSecondaryContainerDark = Color(0xFFFFCEC6)
val tertiaryDark = Color(0xFFF4BD6A)
val onTertiaryDark = Color(0xFF442B00)
val tertiaryContainerDark = Color(0xFF6A4600)
val onTertiaryContainerDark = Color(0xFFFFE8CC)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1F0F0D)
val onBackgroundDark = Color(0xFFFBDBD6)
val surfaceDark = Color(0xFF1F0F0D)
val onSurfaceDark = Color(0xFFFBDBD6)
val surfaceVariantDark = Color(0xFF5C403B)
val onSurfaceVariantDark = Color(0xFFE6BDB7)
val outlineDark = Color(0xFFAD8882)
val outlineVariantDark = Color(0xFF5C403B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFFBDBD6)
val inverseOnSurfaceDark = Color(0xFF3F2C29)
val inversePrimaryDark = Color(0xFFBE0F07)


